# dream-dao/src/main/resources/db.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dreamdb?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456@123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml  # 如果使用 XML mapper
  type-aliases-package: com.dreampass.dao.model    # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true         # 数据库下划线自动映射为驼峰字段