package com.dreampass.dao.model;

import java.util.Date;

public class AccountProfilePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_profile.id
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_profile.tenant_id
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_profile.account_name
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_profile.avatar_key
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    private String avatarKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_profile.bio
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_profile.create_time
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_profile.update_time
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_profile.delete_time
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_profile.ext
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    private String ext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_profile.id
     *
     * @return the value of account_profile.id
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_profile.id
     *
     * @param id the value for account_profile.id
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_profile.tenant_id
     *
     * @return the value of account_profile.tenant_id
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_profile.tenant_id
     *
     * @param tenantId the value for account_profile.tenant_id
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_profile.account_name
     *
     * @return the value of account_profile.account_name
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_profile.account_name
     *
     * @param accountName the value for account_profile.account_name
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_profile.avatar_key
     *
     * @return the value of account_profile.avatar_key
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public String getAvatarKey() {
        return avatarKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_profile.avatar_key
     *
     * @param avatarKey the value for account_profile.avatar_key
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public void setAvatarKey(String avatarKey) {
        this.avatarKey = avatarKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_profile.bio
     *
     * @return the value of account_profile.bio
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_profile.bio
     *
     * @param bio the value for account_profile.bio
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public void setBio(String bio) {
        this.bio = bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_profile.create_time
     *
     * @return the value of account_profile.create_time
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_profile.create_time
     *
     * @param createTime the value for account_profile.create_time
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_profile.update_time
     *
     * @return the value of account_profile.update_time
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_profile.update_time
     *
     * @param updateTime the value for account_profile.update_time
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_profile.delete_time
     *
     * @return the value of account_profile.delete_time
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_profile.delete_time
     *
     * @param deleteTime the value for account_profile.delete_time
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_profile.ext
     *
     * @return the value of account_profile.ext
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_profile.ext
     *
     * @param ext the value for account_profile.ext
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    public void setExt(String ext) {
        this.ext = ext;
    }
}