package com.dreampass.dao.model;

import java.util.Date;

public class AccountRoleRefPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_role_ref.id
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_role_ref.tenant_id
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_role_ref.account_name
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_role_ref.role_code
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_role_ref.create_time
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_role_ref.update_time
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_role_ref.delete_time
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_role_ref.id
     *
     * @return the value of account_role_ref.id
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_role_ref.id
     *
     * @param id the value for account_role_ref.id
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_role_ref.tenant_id
     *
     * @return the value of account_role_ref.tenant_id
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_role_ref.tenant_id
     *
     * @param tenantId the value for account_role_ref.tenant_id
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_role_ref.account_name
     *
     * @return the value of account_role_ref.account_name
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_role_ref.account_name
     *
     * @param accountName the value for account_role_ref.account_name
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_role_ref.role_code
     *
     * @return the value of account_role_ref.role_code
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_role_ref.role_code
     *
     * @param roleCode the value for account_role_ref.role_code
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_role_ref.create_time
     *
     * @return the value of account_role_ref.create_time
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_role_ref.create_time
     *
     * @param createTime the value for account_role_ref.create_time
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_role_ref.update_time
     *
     * @return the value of account_role_ref.update_time
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_role_ref.update_time
     *
     * @param updateTime the value for account_role_ref.update_time
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_role_ref.delete_time
     *
     * @return the value of account_role_ref.delete_time
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_role_ref.delete_time
     *
     * @param deleteTime the value for account_role_ref.delete_time
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}