package com.dreampass.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrderPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.tenant_id
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.code
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.name
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.img_url
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.price
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_status
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.creator
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.updater
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.update_time
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.delete_time
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.description
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.tenant_id
     *
     * @return the value of orders.tenant_id
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.tenant_id
     *
     * @param tenantId the value for orders.tenant_id
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.code
     *
     * @return the value of orders.code
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.code
     *
     * @param code the value for orders.code
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.name
     *
     * @return the value of orders.name
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.name
     *
     * @param name the value for orders.name
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.img_url
     *
     * @return the value of orders.img_url
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.img_url
     *
     * @param imgUrl the value for orders.img_url
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.price
     *
     * @return the value of orders.price
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.price
     *
     * @param price the value for orders.price
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_status
     *
     * @return the value of orders.order_status
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_status
     *
     * @param orderStatus the value for orders.order_status
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.creator
     *
     * @return the value of orders.creator
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.creator
     *
     * @param creator the value for orders.creator
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.updater
     *
     * @return the value of orders.updater
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.updater
     *
     * @param updater the value for orders.updater
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.update_time
     *
     * @return the value of orders.update_time
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.update_time
     *
     * @param updateTime the value for orders.update_time
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.delete_time
     *
     * @return the value of orders.delete_time
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.delete_time
     *
     * @param deleteTime the value for orders.delete_time
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.description
     *
     * @return the value of orders.description
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.description
     *
     * @param description the value for orders.description
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }
}