package com.dreampass.dao.model;

import java.util.Date;

public class ResourcePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.tenant_id
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    private Long tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.name
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.type
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.path
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.method
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.parent_id
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.description
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.visible
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    private Boolean visible;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.create_time
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.update_time
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.delete_time
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.tenant_id
     *
     * @return the value of resource.tenant_id
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.tenant_id
     *
     * @param tenantId the value for resource.tenant_id
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.name
     *
     * @return the value of resource.name
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.name
     *
     * @param name the value for resource.name
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.type
     *
     * @return the value of resource.type
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.type
     *
     * @param type the value for resource.type
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.path
     *
     * @return the value of resource.path
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.path
     *
     * @param path the value for resource.path
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.method
     *
     * @return the value of resource.method
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.method
     *
     * @param method the value for resource.method
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.parent_id
     *
     * @return the value of resource.parent_id
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.parent_id
     *
     * @param parentId the value for resource.parent_id
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.description
     *
     * @return the value of resource.description
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.description
     *
     * @param description the value for resource.description
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.visible
     *
     * @return the value of resource.visible
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public Boolean getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.visible
     *
     * @param visible the value for resource.visible
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.create_time
     *
     * @return the value of resource.create_time
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.create_time
     *
     * @param createTime the value for resource.create_time
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.update_time
     *
     * @return the value of resource.update_time
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.update_time
     *
     * @param updateTime the value for resource.update_time
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.delete_time
     *
     * @return the value of resource.delete_time
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.delete_time
     *
     * @param deleteTime the value for resource.delete_time
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}