package com.dreampass.dao.mapper;

import com.dreampass.dao.model.AccountPo;
import com.dreampass.dao.model.AccountPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Jul 30 14:12:42 CST 2025
     */
    long countByExample(AccountPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Jul 30 14:12:42 CST 2025
     */
    int deleteByExample(AccountPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Jul 30 14:12:42 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Jul 30 14:12:42 CST 2025
     */
    int insert(AccountPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Jul 30 14:12:42 CST 2025
     */
    int insertSelective(AccountPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Jul 30 14:12:42 CST 2025
     */
    List<AccountPo> selectByExample(AccountPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Jul 30 14:12:42 CST 2025
     */
    AccountPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Jul 30 14:12:42 CST 2025
     */
    int updateByExampleSelective(@Param("row") AccountPo row, @Param("example") AccountPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Jul 30 14:12:42 CST 2025
     */
    int updateByExample(@Param("row") AccountPo row, @Param("example") AccountPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Jul 30 14:12:42 CST 2025
     */
    int updateByPrimaryKeySelective(AccountPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Wed Jul 30 14:12:42 CST 2025
     */
    int updateByPrimaryKey(AccountPo row);
}