package com.dreampass.dao.mapper;

import com.dreampass.dao.model.AccountRoleRefPo;
import com.dreampass.dao.model.AccountRoleRefPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountRoleRefPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role_ref
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    long countByExample(AccountRoleRefPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role_ref
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    int deleteByExample(AccountRoleRefPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role_ref
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role_ref
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    int insert(AccountRoleRefPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role_ref
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    int insertSelective(AccountRoleRefPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role_ref
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    List<AccountRoleRefPo> selectByExample(AccountRoleRefPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role_ref
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    AccountRoleRefPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role_ref
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    int updateByExampleSelective(@Param("row") AccountRoleRefPo row, @Param("example") AccountRoleRefPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role_ref
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    int updateByExample(@Param("row") AccountRoleRefPo row, @Param("example") AccountRoleRefPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role_ref
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    int updateByPrimaryKeySelective(AccountRoleRefPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role_ref
     *
     * @mbg.generated Wed Jul 30 23:02:37 CST 2025
     */
    int updateByPrimaryKey(AccountRoleRefPo row);
}