package com.dreampass.dao.mapper;

import com.dreampass.dao.model.AccountProfilePo;
import com.dreampass.dao.model.AccountProfilePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountProfilePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_profile
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    long countByExample(AccountProfilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_profile
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    int deleteByExample(AccountProfilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_profile
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_profile
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    int insert(AccountProfilePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_profile
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    int insertSelective(AccountProfilePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_profile
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    List<AccountProfilePo> selectByExampleWithBLOBs(AccountProfilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_profile
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    List<AccountProfilePo> selectByExample(AccountProfilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_profile
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    AccountProfilePo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_profile
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    int updateByExampleSelective(@Param("row") AccountProfilePo row, @Param("example") AccountProfilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_profile
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("row") AccountProfilePo row, @Param("example") AccountProfilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_profile
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    int updateByExample(@Param("row") AccountProfilePo row, @Param("example") AccountProfilePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_profile
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    int updateByPrimaryKeySelective(AccountProfilePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_profile
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(AccountProfilePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_profile
     *
     * @mbg.generated Fri Aug 22 16:32:24 CST 2025
     */
    int updateByPrimaryKey(AccountProfilePo row);
}