package com.dreampass.dao.mapper;

import com.dreampass.dao.model.OrderPo;
import com.dreampass.dao.model.OrderPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    long countByExample(OrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    int deleteByExample(OrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    int insert(OrderPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    int insertSelective(OrderPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    List<OrderPo> selectByExampleWithBLOBs(OrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    List<OrderPo> selectByExample(OrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    OrderPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    int updateByExampleSelective(@Param("row") OrderPo row, @Param("example") OrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("row") OrderPo row, @Param("example") OrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    int updateByExample(@Param("row") OrderPo row, @Param("example") OrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    int updateByPrimaryKeySelective(OrderPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(OrderPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Sat Aug 09 20:31:32 CST 2025
     */
    int updateByPrimaryKey(OrderPo row);
}