package com.dreampass.dao.mapper;

import com.dreampass.dao.model.ResourcePo;
import com.dreampass.dao.model.ResourcePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourcePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    long countByExample(ResourcePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    int deleteByExample(ResourcePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    int insert(ResourcePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    int insertSelective(ResourcePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    List<ResourcePo> selectByExample(ResourcePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    ResourcePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    int updateByExampleSelective(@Param("row") ResourcePo row, @Param("example") ResourcePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    int updateByExample(@Param("row") ResourcePo row, @Param("example") ResourcePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    int updateByPrimaryKeySelective(ResourcePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Tue Jul 29 22:34:28 CST 2025
     */
    int updateByPrimaryKey(ResourcePo row);
}