package com.dreampass.dao.mapper;

import com.dreampass.dao.model.RolePo;
import com.dreampass.dao.model.RolePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Jul 30 20:02:35 CST 2025
     */
    long countByExample(RolePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Jul 30 20:02:35 CST 2025
     */
    int deleteByExample(RolePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Jul 30 20:02:35 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Jul 30 20:02:35 CST 2025
     */
    int insert(RolePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Jul 30 20:02:35 CST 2025
     */
    int insertSelective(RolePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Jul 30 20:02:35 CST 2025
     */
    List<RolePo> selectByExample(RolePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Jul 30 20:02:35 CST 2025
     */
    RolePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Jul 30 20:02:35 CST 2025
     */
    int updateByExampleSelective(@Param("row") RolePo row, @Param("example") RolePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Jul 30 20:02:35 CST 2025
     */
    int updateByExample(@Param("row") RolePo row, @Param("example") RolePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Jul 30 20:02:35 CST 2025
     */
    int updateByPrimaryKeySelective(RolePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Wed Jul 30 20:02:35 CST 2025
     */
    int updateByPrimaryKey(RolePo row);
}