package com.dreampass.dao.mapper;

import com.dreampass.dao.model.RoleResourceRefPo;
import com.dreampass.dao.model.RoleResourceRefPoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleResourceRefPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_ref
     *
     * @mbg.generated Thu Jul 31 08:07:25 CST 2025
     */
    long countByExample(RoleResourceRefPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_ref
     *
     * @mbg.generated Thu Jul 31 08:07:25 CST 2025
     */
    int deleteByExample(RoleResourceRefPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_ref
     *
     * @mbg.generated Thu Jul 31 08:07:25 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_ref
     *
     * @mbg.generated Thu Jul 31 08:07:25 CST 2025
     */
    int insert(RoleResourceRefPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_ref
     *
     * @mbg.generated Thu Jul 31 08:07:25 CST 2025
     */
    int insertSelective(RoleResourceRefPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_ref
     *
     * @mbg.generated Thu Jul 31 08:07:25 CST 2025
     */
    List<RoleResourceRefPo> selectByExample(RoleResourceRefPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_ref
     *
     * @mbg.generated Thu Jul 31 08:07:25 CST 2025
     */
    RoleResourceRefPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_ref
     *
     * @mbg.generated Thu Jul 31 08:07:25 CST 2025
     */
    int updateByExampleSelective(@Param("row") RoleResourceRefPo row, @Param("example") RoleResourceRefPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_ref
     *
     * @mbg.generated Thu Jul 31 08:07:25 CST 2025
     */
    int updateByExample(@Param("row") RoleResourceRefPo row, @Param("example") RoleResourceRefPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_ref
     *
     * @mbg.generated Thu Jul 31 08:07:25 CST 2025
     */
    int updateByPrimaryKeySelective(RoleResourceRefPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_ref
     *
     * @mbg.generated Thu Jul 31 08:07:25 CST 2025
     */
    int updateByPrimaryKey(RoleResourceRefPo row);
}